'use strict';

import createId from '../utils/id';

class Property {
  /**
   * @constructor
   */
  constructor(options = {}) {
    this.id = options.id || createId();
    // 取消默认转小写的操作
    // this.key = (options.key || 'new').toLowerCase();
    this.key = (options.key || 'new');
    this.type = (options.type || '');
    this.defaultValue = options.defaultValue || '';
    this.limitMin = options.limitMin || '';
    this.limitMax = options.limitMax || '';
    this.isRequired = options.isRequired || false;
    this.isAutoGenerated = options.isAutoGenerated || false;
    this.isSystem = options.isSystem || false;
    this.description = options.description || '';
  }
  get copy() {
    return new Property((JSON.parse(JSON.stringify(this))));
  }
}

export default Property;
